server:
  port: 8282

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org.mdmi: ${LOGGING_LEVEL_MDMI:INFO}
    org.springframework: ${LOGGING_LEVEL_SPRING:info}
    com.google: ${LOGGING_LEVEL_JSCOMP:OFF}

fhirterminology:
    userName: ${FHIR_TERMINOLOGY_NAME:user}
    password: ${FHIR_TERMINOLOGY_PASSWORD:user}
    url: ${FHIR_TERMINOLOGY_URL:http://terminologyservice.mdixinc.net:8080/fhir}

origins:
  url: ""
