server:
  port: 8282

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:trace}
    org.mdmi: ${LOGGING_LEVEL_MDMI:trace}
    org.springframework: ${LOGGING_LEVEL_SPRING:info}

fhirterminology:
    userName: user
    password: user
    url: http://terminologyservice.mdixinc.net:8080/fhir

origins:
  url: ""
